### ISSUE TITLE
running the app encounters error

### ISSUE THREAD

**Issue by briteming** [xioren/uvd#6]
hi.

yudeMacBook-Air:src ym$ ./uvd --help
could not import: X509_check_host
yudeMacBook-Air:src ym$

how to fix it? tks

**Comment by vercingetorx** [comment]
Hi, this seems to be a problem with the Nim language on Mac. More information [here](https://github.com/nim-lang/nimble/issues/789).

**Comment by briteming** [comment]
hi.

now the issue is fixed.but 
yudeMacBook-Air:src ym$ ./uvd https://www.youtube.com/watch?v=DjiGV8KqJPs
[uvd] youtube
[info] video id: DjiGV8KqJPs

[error] Invalid argument
[error] failed to obtain video metadata
yudeMacBook-Air:src ym$

what does ' Invalid argument' mean?

**Comment by vercingetorx** [comment]
I cannot reproduce the error as I don't have a Mac and for what it's worth I have not tested uvd on Mac so I make no guarantees it works. Running uvd with that url on my pc works fine. Can you run `./uvd --debug https://www.youtube.com/watch?v=DjiGV8KqJPs` and post the output please.

**Comment by briteming** [comment]
hi。

i'm in china. in china youtube.com is blocked by gfw. u are in korea?

so firstly i launched openvpn, then ran ./uvd https://www.youtube.com/watch?v=DjiGV8KqJPs but the download isn't complete,so i exited openvpn,use proxychains4:
proxychains4 ./uvd https://www.youtube.com/watch?v=DjiGV8KqJPs

now it can be downloaded successfully.

**Comment by vercingetorx** [comment]
Okay glad you got it figured it out.

**Comment by briteming** [comment]
but the video is mkv format. i want mp4 format. how to set in ./uvd?

**Comment by vercingetorx** [comment]
Many youtube streams can not be put into mp4 containers so uvd uses mkv as it is the easiest and most compatible. As of now there is no way to output to mp4 using uvd; you would have to do that manually. If there is enough demand for it I may consider adding mp4 functionality in the future.

**Comment by briteming** [comment]
i use ffmpeg command:
ffmpeg -i '陈瑞  [ 我是一只修行千年的狐 ] [DjiGV8KqJPs].mkv' -vcodec copy -acodec copy 白狐.mp4

it's completed instantly.

thank u very much if u can add mp4 functionality in the future.
